services:
  mysql:
    image: mysql:8.0
    container_name: certimate-manager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: certimate_manager
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - certimate-manager-mysql-data:/var/lib/mysql

volumes:
  certimate-manager-mysql-data:
